iam:
  microgateway:
    spec:
      source:
        repoURL: https://ergon.github.io/airlock-helm-charts
        targetRevision: 2.2.1
        chart: microgateway

    resources:
      path: data/authentication/microgateway/

    helm:
      values:
        fullnameOverride: iam-microgateway

        resources:
          limits:
            memory: 512Mi

        podAnnotations:
          prometheus.io/scrape: "true"
          prometheus.io/port: "9102"

        service:
          annotations:
            prometheus.io/scrape: "true"
            prometheus.io/port: "9102"

        extraVolumes:
          - name: iam-mapping-template-adminapp
            configMap:
              name: iam-microgateway-mapping-template-adminapp
          - name: iam-mapping-template-loginapp
            configMap:
              name: iam-microgateway-mapping-template-loginapp
          - name: iam-mapping-template-loginapp-rest-protected
            configMap:
              name: iam-microgateway-mapping-template-loginapp-rest-protected
          - name: iam-mapping-template-loginapp-rest-public
            configMap:
              name: iam-microgateway-mapping-template-loginapp-rest-public
          - name: iam-microgateway-openapi-login-rest
            configMap:
              name: iam-microgateway-openapi-login-rest
        extraVolumeMounts:
          - name: iam-mapping-template-adminapp
            mountPath: /config/templates/iam-adminapp.xml
            subPath: iam-adminapp.xml
          - name: iam-mapping-template-loginapp
            mountPath: /config/templates/iam-loginapp.xml
            subPath: iam-loginapp.xml
          - name: iam-mapping-template-loginapp-rest-protected
            mountPath: /config/templates/iam-loginapp-rest-protected.xml
            subPath: iam-loginapp-rest-protected.xml
          - name: iam-mapping-template-loginapp-rest-public
            mountPath: /config/templates/iam-loginapp-rest-public.xml
            subPath: iam-loginapp-rest-public.xml
          - name: iam-microgateway-openapi-login-rest
            mountPath: /config/openapi/openapi-loginapp-rest.json
            subPath: openapi-loginapp-rest.json

        config:
          passphrase:
            useExistingSecret: true
            secretName: "microgateway-passphrase"

          env:
            configbuilder:
              - name: LOG_LEVEL
                value: info
              - name: OPERATIONAL_MODE
                value: production
              - name: COOKIE_NAME
                valueFrom:
                  secretKeyRef:
                    name: jwt-secret
                    key: COOKIE_NAME

          dsl:
            log:
              level: ${LOG_LEVEL:-info}

            session:
              redis_hosts: [redis-master]

            remote_ip:
              header: X-Forwarded-For
              internal_proxies:
                - 10.0.0.0/8
                - 172.16.0.0/12
                - 192.168.0.0/16

            expert_settings:
              security_gate: |
                CorrelationId.Extraction.0.Request.Header.Pattern       "^X-Request-ID: ([[:graph:]]+)$"
                CorrelationId.Extraction.0.Request.Header.IgnoreCase    "TRUE"
                CorrelationId.Extraction.0.Request.Header.Template      "$1"

                RolesWhitelist.Pattern                "^authenticated$"

            apps:
              - virtual_host:
                  name: vh-iam
                  expert_settings:
                    apache: |
                      # default redirect
                      RewriteRule ^/$ https://%{ENV:HTTP_HOST_NOPORT}/auth/portal [R=303,NE]
                mappings:
                  - mapping_template_file: /config/templates/iam-loginapp.xml
                    entry_path:
                      value: /auth/
                    backend_path: /auth-login/
                    operational_mode: ${OPERATIONAL_MODE:-production}
                    cookies:
                      passthrough:
                        pattern: ^${COOKIE_NAME}$
                    allow_rules:
                      - name: "Loginapp Single Page Application"
                        enabled: true
                    csrf_token:
                      enabled: false
                    backend:
                      name: beg-iam
                      hosts:
                        - protocol: "https"
                          name: iam-0.iam
                          port: 8443
                  - mapping_template_file: /config/templates/iam-loginapp-rest-public.xml
                    entry_path:
                      value: /auth/rest/public
                    backend_path: /auth-login/rest/public
                    operational_mode: ${OPERATIONAL_MODE:-production}
                    cookies:
                      passthrough:
                        pattern: ^${COOKIE_NAME}$
                    api_security:
                      openapi:
                        spec_file: /config/openapi/openapi-loginapp-rest.json
                    backend:
                      name: beg-iam
                      hosts:
                        - protocol: "https"
                          name: iam-0.iam
                          port: 8443
                  - mapping_template_file: /config/templates/iam-loginapp-rest-protected.xml
                    entry_path:
                      value: /auth/rest/protected
                    backend_path: /auth-login/rest/protected
                    operational_mode: ${OPERATIONAL_MODE:-production}
                    cookies:
                      passthrough:
                        pattern: ^${COOKIE_NAME}$
                    api_security:
                      openapi:
                        spec_file: /config/openapi/openapi-loginapp-rest.json
                    backend:
                      name: beg-iam
                      hosts:
                        - protocol: "https"
                          name: iam-0.iam
                          port: 8443
                  - mapping_template_file: /config/templates/iam-adminapp.xml
                    entry_path:
                      value: /auth-admin/
                    operational_mode: ${OPERATIONAL_MODE:-production}
                    backend:
                      name: beg-iam
                      hosts:
                        - protocol: "https"
                          name: iam-0.iam
                          port: 8443
