iam:
  microgateway:
    spec:
      source:
        repoURL: https://ergon.github.io/airlock-helm-charts
        targetRevision: 3.0.4
        chart: microgateway

    resources:
      path: data/authentication/microgateway/

    helm:
      values:
        image:
          tag: "3.1"

        fullnameOverride: iam-microgateway

        resources:
          limits:
            memory: 512Mi

        podAnnotations:
          prometheus.io/scrape: "true"
          prometheus.io/port: "9102"

        service:
          annotations:
            prometheus.io/scrape: "true"
            prometheus.io/port: "9102"

        extraVolumes:
          - name: iam-mapping-template-adminapp
            configMap:
              name: iam-microgateway-mapping-template-adminapp
          - name: iam-mapping-template-loginapp
            configMap:
              name: iam-microgateway-mapping-template-loginapp
          - name: iam-mapping-template-loginapp-rest-protected
            configMap:
              name: iam-microgateway-mapping-template-loginapp-rest-protected
          - name: iam-mapping-template-loginapp-rest-public
            configMap:
              name: iam-microgateway-mapping-template-loginapp-rest-public
          - name: iam-microgateway-openapi-login-rest
            configMap:
              name: iam-microgateway-openapi-login-rest
        extraVolumeMounts:
          - name: iam-mapping-template-adminapp
            mountPath: /config/templates/iam-adminapp.xml
            subPath: iam-adminapp.xml
          - name: iam-mapping-template-loginapp
            mountPath: /config/templates/iam-loginapp.xml
            subPath: iam-loginapp.xml
          - name: iam-mapping-template-loginapp-rest-protected
            mountPath: /config/templates/iam-loginapp-rest-protected.xml
            subPath: iam-loginapp-rest-protected.xml
          - name: iam-mapping-template-loginapp-rest-public
            mountPath: /config/templates/iam-loginapp-rest-public.xml
            subPath: iam-loginapp-rest-public.xml
          - name: iam-microgateway-openapi-login-rest
            mountPath: /config/openapi/openapi-loginapp-rest.json
            subPath: openapi-loginapp-rest.json

        ingress:
          enabled: true
          annotations:
            kubernetes.io/ingress.class: "nginx"
            nginx.ingress.kubernetes.io/backend-protocol: https
            nginx.ingress.kubernetes.io/use-regex: "true"
          path: "^(?:/$|/auth/|/auth-admin/)"
          pathType: Prefix
          servicePortName: https

        config:
          passphrase:
            useExistingSecret: true
            secretName: microgateway-passphrase

          license:
            useExistingSecret: true
            secretName: microgateway-license

          env:
            configbuilder:
              - name: COOKIE_NAME
                valueFrom:
                  secretKeyRef:
                    name: jwt-secret
                    key: COOKIE_NAME

          dslConfigMap: iam-microgateway-config
