mariadb:
  spec:
    source:
      repoURL: https://charts.bitnami.com/bitnami
      targetRevision: 9.4.3
      chart: mariadb

  resources:
    path: data/authentication/mariadb/

  helm:
    values:
      initdbScriptsConfigMap: iam-mariadb-sql-files

      primary:
        persistence:
          size: 100M

      auth:
        database: iamdb
        username: airlock
        existingSecret: mariadb-secret
