---
apiVersion: v1
kind: Pod
metadata:
  labels:
    run: data-pod
  name: data-pod
spec:
  imagePullSecrets:
    - name: dockerregcred
  initContainers:
    - name: iam-init
      image: docker.io/ergon/airlock-iam:latest-7.4
      imagePullPolicy: IfNotPresent
      args: [ "init" ]
      volumeMounts:
        - name: data
          mountPath: /home/airlock/iam/
          subPath: iam
  containers:
    - name: data-container
      image: docker.io/alpine
      imagePullPolicy: IfNotPresent
      command: [ "/bin/sh" ]
      args: [ "-c", "tail -f /dev/null" ]
      volumeMounts:
        - name: data
          mountPath: /data/
  volumes:
    - name: data
      persistentVolumeClaim:
        claimName: data-claim