---
apiVersion: v1
kind: Pod
metadata:
  labels:
    run: data-pod
  name: data-pod
spec:
  imagePullSecrets:
    - name: dockerregcred
  initContainers:
    - name: iam-init
      image: docker.io/ergon/airlock-iam:latest-7.4
      imagePullPolicy: IfNotPresent
      # TODO:
      # Not required anymore with AI-13645 (IAM 7.4)
      # With IAM 7.4 no 'command', but 'args: [ "init" ]'
      # https://github.com/ergon/airlock-minikube-example/blob/9f56124e767ec630d042ec43b0d8c4ae4b251f89/data/data-pod.yaml
      command:
        - bash
        - -c
        - |
          if [ ! -d /home/airlock/iam/instances ]; then
            /iam_entrypoint init
          fi
      volumeMounts:
        - name: data
          mountPath: /home/airlock/iam/
          subPath: iam
  containers:
    - name: data-container
      image: docker.io/alpine
      imagePullPolicy: IfNotPresent
      command: [ "/bin/sh" ]
      args: [ "-c", "tail -f /dev/null" ]
      volumeMounts:
        - name: data
          mountPath: /data/
  volumes:
    - name: data
      persistentVolumeClaim:
        claimName: data-claim