---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-claim
spec:
  storageClassName: ""
  selector: 
    matchLabels: 
      vol-type: local
      vol-name: data-vol
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 500Mi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-vol
  labels:
    vol-type: local
    vol-name: data-vol
spec:
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/data/data-vol"
  persistentVolumeReclaimPolicy: Retain