apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: "{{ .Values.grafana.spec.source.repoURL }}"
    targetRevision: "{{ .Values.grafana.spec.source.targetRevision }}"
    chart: "{{ .Values.grafana.spec.source.chart }}"

    helm:
      values: |{{ toYaml .Values.grafana.helm.values | nindent 8 }}

  destination:
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy: {{ toYaml .Values.spec.syncPolicy | nindent 4 }}
