---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-dashboard-airlock-microgateway
  annotations:
    helm.sh/hook: pre-install
    helm.sh/hook-weight: "-90"
data: {{ (.Files.Glob "config/grafana/*").AsConfig | nindent 2 }}
