---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 14.3.0
    chart: prometheus

    helm:
      values: |
        imagePullSecrets:
          - name: dockerregcred

        alertmanager:
          enabled: false
        alertmanagerFiles:
          alertmanager.yml: ""
        kubeStateMetrics:
          enabled: false
        nodeExporter:
          enabled: false
        pushgateway:
          enabled: false

        server:
          persistentVolume:
            size: 100M

  destination:
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy: {{ toYaml .Values.spec.syncPolicy | nindent 4 }}
