apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: community
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/ergon/airlock-minikube-example.git
    targetRevision: v3.0.0
    path: apps/minikube-example/

    helm:
      values: |
        spec:
          source:
            repoURL: https://github.com/ergon/airlock-minikube-example.git
            targetRevision: v3.0.0

        microgateway:
          license:
            secretName:
            
        authentication:
          enabled: false

        logging:
          enabled: true

        monitoring:
          enabled: true

        backend:
          enabled: true

  destination:
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    automated:
      selfHeal: true
      prune: true
