apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/dieti80/airlock-minikube-example.git
    targetRevision: HEAD
    path: apps/minikube-example/

    helm:
      values: |
        spec:
          source:
            repoURL: https://github.com/dieti80/airlock-minikube-example.git
            targetRevision: HEAD

          syncPolicy:
            automated:
              selfHeal: false
              prune: false

        microgateway:
          license:
            secretName: microgateway-license
            
        authentication:
          enabled: true

        logging:
          enabled: true

        monitoring:
          enabled: true

        backend:
          enabled: true

  destination:
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    automated:
      selfHeal: false
      prune: false
