---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: microgateway-echoserver
  labels:
    app: microgateway-echoserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: microgateway-echoserver
  template:
    metadata:
      labels:
        app: microgateway-echoserver
    spec:
      imagePullSecrets:
        - name: dockerregcred
      containers:
        - name: microgateway-echoserver
          image: ergon/airlock-microgateway:1.0
          imagePullPolicy: IfNotPresent
          env:
            - name: TZ
              valueFrom:
                configMapKeyRef:
                  name: generic-parameters
                  key: TZ
            - name: ALG_CFG_OPERATIONAL_MODE
              value: integration
          ports:
            - name: https
              containerPort: 8443
          volumeMounts:
            - name: config
              mountPath: /config/config.yaml
              subPath: config.yaml
              readOnly: true
            - name: secret
              mountPath: /secret/config/
              readOnly: true
          livenessProbe:
            failureThreshold: 9
            timeoutSeconds: 5
            httpGet:
              path: /healthz
              port: https
              scheme: HTTPS
            initialDelaySeconds: 90
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /healthz
              port: https
              scheme: HTTPS
            initialDelaySeconds: 10
          lifecycle:
            preStop:
              exec:
                command:
                  - /usr/bin/sleep
                  - "10"
          resources:
            requests:
              memory: 256Mi
              cpu: 30m
            limits:
              memory: 4048Mi
      volumes:
        - name: config
          configMap:
            name: microgateway-echoserver-config
        - name: secret
          secret:
            secretName: microgateway-secret
---
apiVersion: v1
kind: Service
metadata:
  name: microgateway-echoserver
  labels:
    app: microgateway-echoserver
spec:
  selector:
    app: microgateway-echoserver
  ports:
    - name: https
      port: 8443
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: microgateway-echoserver-config
data:
  config.yaml: |
    license_file: /secret/config/license

    log:
      level: info

    session:
      redis_hosts:
      - 'redis:6379'
      store_mode: server
      encryption_passphrase_file: /secret/config/passphrase

    expert_settings:
      apache: |
        RemoteIPHeader x-real-ip
        RemoteIPInternalProxy 10.0.0.0/8
        RemoteIPInternalProxy 172.16.0.0/12
        RemoteIPInternalProxy 192.168.0.0/16
      security_gate: |
        # TODO:
        # Needed until AP-21937 is available.
        # Attention: Request Header Whitelist must allow this header
        Request.Logging.Headers.Enable        "TRUE"
        Request.Logging.Headers.Mode          "request"
        Request.Logging.Headers.Pattern       "^x-request-id:"
        Request.Logging.Headers.IgnoreCase    "TRUE"
        Request.Logging.Headers.InvertPattern "FALSE"

    apps:
    - virtual_host:
        name: vh-echoserver
      mappings:
      - name: echoserver
        entry_path: /
        session_handling: enforce_session
        operational_mode: @@ALG_CFG_OPERATIONAL_MODE@@
        threat_handling: notify
        deny_rules:
        - level: strict
          enabled: true
        expert_settings:
          security_gate: |
            Backend.AddEnvironmentCookies         "TRUE"
            Cookie.PassthroughSelector.Pattern    "^.*$"
            Cookie.PassthroughSelector.IgnoreCase "TRUE"
      backend:
        name: beg-echoserver
        protocol: 'http'
        hostname: echoserver
        port: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-microgateway-echoserver
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: https
spec:
  rules:
    - http:
        paths:
          - path: /echo
            pathType: Prefix
            backend:
              service:
                name: microgateway-echoserver
                port:
                  number: 8443