{
 "title": "Airlock Microgateway",
 "tags": [ "airlock-microgateway" ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "Kubernetes namespace",
    "query": {
     "query": "label_values(kubernetes_namespace)"
    }
   },
   {
    "name": "service_name",
    "label": "Kubernetes service",
    "query": {
     "query": "label_values(kubernetes_service_name)"
    }
   },
   {
    "name": "pod_name",
    "label": "Kubernetes pod",
    "query": {
     "query": "label_values(kubernetes_pod_name)"
    }
   }
  ]
 },
 "panels": [
  { "title": "System", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Throughput",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "max(airlock_throughput_licensed{kubernetes_service_name=~\".+\"})",
     "legendFormat": "Licensed"
    },
    {
     "expr": "sum(airlock_throughput{kubernetes_service_name=~\".+\"})",
     "legendFormat": "Total"
    },
    {
     "expr": "sum (airlock_throughput{kubernetes_service_name=~\"$service_name\"}) by (kubernetes_service_name)",
     "legendFormat": "Service: {{kubernetes_service_name}}"
    }
   ]
  },
  {
   "title": "Workload by service",
   "type": "graph",
   "gridPos": { "h": 9, "w": 7, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "yaxes": [
    { "format": "percentunit", "label": "Workload" }
   ],
   "targets": [
    {
     "expr": "avg(airlock_workload_ratio{kubernetes_namespace=~\"$namespace\", kubernetes_service_name=~\"$service_name\"}) by (kubernetes_service_name)",
     "legendFormat": "{{kubernetes_service_name}}"
    }
   ]
  },
  {
   "title": "Workload by pod",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 7, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "yaxes": [
    { "format": "percentunit", "label": "Workload" }
   ],
   "targets": [
    {
     "expr": "airlock_workload_ratio{kubernetes_namespace=~\"$namespace\", kubernetes_pod_name=~\"$pod_name\"}",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Workload by pod (current)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 9, "x": 15, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "yaxes": [
    { "format": "percentunit", "label": "Workload" }
   ],
   "targets": [
    {
     "expr": "airlock_workload_ratio{kubernetes_namespace=~\"$namespace\", kubernetes_pod_name=~\"$pod_name\"}",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  { "title": "Requests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Request rate by namespace",
   "type": "graph",
   "gridPos": { "h": 9, "w": 7, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_requests_allowed_total{kubernetes_namespace=~\"$namespace\", kubernetes_service_name=~\".+\"}[2m])) by (kubernetes_namespace) /\r\nsum(rate(http_requests_duration_seconds_count{kubernetes_namespace=~\"$namespace\", kubernetes_service_name=~\".+\"}[2m])) by (kubernetes_namespace)",
     "legendFormat": "Allowed"
    },
    {
     "expr": "sum(rate(http_requests_blocked_total{kubernetes_namespace=~\"$namespace\", kubernetes_service_name=~\".+\"}[2m])) by (kubernetes_namespace) /\r\nsum(rate(http_requests_duration_seconds_count{kubernetes_namespace=~\"$namespace\", kubernetes_service_name=~\".+\"}[2m])) by (kubernetes_namespace)",
     "legendFormat": "Blocked"
    },
    {
     "expr": "sum(rate(http_requests_rejected_total{kubernetes_namespace=~\"$namespace\", kubernetes_service_name=~\".+\"}[2m])) by (kubernetes_namespace) /\r\nsum(rate(http_requests_duration_seconds_count{kubernetes_namespace=~\"$namespace\", kubernetes_service_name=~\".+\"}[2m])) by (kubernetes_namespace)",
     "legendFormat": "Rejected"
    }
   ]
  },
  {
   "title": "Request rate by service",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 7, "y": 20 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_requests_allowed_total{kubernetes_namespace=~\"$namespace\", kubernetes_service_name=~\"$service_name\"}[2m])) by (kubernetes_service_name) /\nsum(rate(http_requests_duration_seconds_count{kubernetes_namespace=~\"$namespace\", kubernetes_service_name=~\"$service_name\"}[2m])) by (kubernetes_service_name)",
     "legendFormat": "Allowed: {{kubernetes_service_name}}"
    },
    {
     "expr": "sum(rate(http_requests_blocked_total{kubernetes_namespace=~\"$namespace\", kubernetes_service_name=~\"$service_name\"}[2m])) by (kubernetes_service_name) /\nsum(rate(http_requests_duration_seconds_count{kubernetes_namespace=~\"$namespace\", kubernetes_service_name=~\"$service_name\"}[2m])) by (kubernetes_service_name)",
     "legendFormat": "Blocked: {{kubernetes_service_name}}"
    },
    {
     "expr": "sum(rate(http_requests_rejected_total{kubernetes_namespace=~\"$namespace\", kubernetes_service_name=~\"$service_name\"}[2m])) by (kubernetes_service_name) /\nsum(rate(http_requests_duration_seconds_count{kubernetes_namespace=~\"$namespace\", kubernetes_service_name=~\"$service_name\"}[2m])) by (kubernetes_service_name)\n",
     "legendFormat": "Rejected: {{kubernetes_service_name}}"
    }
   ]
  },
  {
   "title": "Request rate by pod",
   "type": "graph",
   "gridPos": { "h": 9, "w": 9, "x": 15, "y": 20 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_requests_allowed_total{kubernetes_namespace=~\"$namespace\", kubernetes_pod_name=~\"$pod_name\"}[2m])) by (kubernetes_pod_name) /\nsum(rate(http_requests_duration_seconds_count{kubernetes_namespace=~\"$namespace\", kubernetes_pod_name=~\"$pod_name\"}[2m])) by (kubernetes_pod_name)",
     "legendFormat": "Allowed: {{kubernetes_pod_name}}"
    },
    {
     "expr": "sum(rate(http_requests_blocked_total{kubernetes_namespace=~\"$namespace\", kubernetes_pod_name=~\"$pod_name\"}[2m])) by (kubernetes_pod_name) /\nsum(rate(http_requests_duration_seconds_count{kubernetes_namespace=~\"$namespace\", kubernetes_pod_name=~\"$pod_name\"}[2m])) by (kubernetes_pod_name)",
     "legendFormat": "Blocked: {{kubernetes_pod_name}}"
    },
    {
     "expr": "sum(rate(http_requests_rejected_total{kubernetes_namespace=~\"$namespace\", kubernetes_pod_name=~\"$pod_name\"}[2m])) by (kubernetes_pod_name) /\nsum(rate(http_requests_duration_seconds_count{kubernetes_namespace=~\"$namespace\", kubernetes_pod_name=~\"$pod_name\"}[2m])) by (kubernetes_pod_name)\n",
     "legendFormat": "Rejected: {{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Requests by namespace",
   "type": "graph",
   "gridPos": { "h": 9, "w": 7, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "avg(http_requests_current{kubernetes_namespace=~\"$namespace\", kubernetes_service_name=~\".+\"}) by (kubernetes_namespace)",
     "legendFormat": "Concurrent"
    },
    {
     "expr": "avg(rate(http_requests_allowed_total{kubernetes_namespace=~\"$namespace\", kubernetes_service_name=~\".+\"}[2m])) by (kubernetes_namespace)",
     "legendFormat": "Allowed"
    },
    {
     "expr": "avg(rate(http_requests_blocked_total{kubernetes_namespace=~\"$namespace\", kubernetes_service_name=~\".+\"}[2m])) by (kubernetes_namespace)",
     "legendFormat": "Blocked"
    },
    {
     "expr": "avg(rate(http_requests_rejected_total{kubernetes_namespace=~\"$namespace\", kubernetes_service_name=~\".+\"}[2m])) by (kubernetes_namespace)",
     "legendFormat": "Rejected"
    }
   ]
  },
  {
   "title": "Requests by service",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 7, "y": 29 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "avg(http_requests_current{kubernetes_namespace=~\"$namespace\", kubernetes_service_name=~\"$service_name\"}) by (kubernetes_service_name)",
     "legendFormat": "Concurrent: {{kubernetes_service_name}}"
    },
    {
     "expr": "avg(rate(http_requests_allowed_total{kubernetes_namespace=~\"$namespace\", kubernetes_service_name=~\"$service_name\"}[2m])) by (kubernetes_service_name)",
     "legendFormat": "Allowed: {{kubernetes_service_name}}"
    },
    {
     "expr": "avg(rate(http_requests_blocked_total{kubernetes_namespace=~\"$namespace\", kubernetes_service_name=~\"$service_name\"}[2m])) by (kubernetes_service_name)",
     "legendFormat": "Blocked: {{kubernetes_service_name}}"
    },
    {
     "expr": "avg(rate(http_requests_rejected_total{kubernetes_namespace=~\"$namespace\", kubernetes_service_name=~\"$service_name\"}[2m])) by (kubernetes_service_name)",
     "legendFormat": "Rejected: {{kubernetes_service_name}}"
    }
   ]
  },
  {
   "title": "Requests by pod",
   "type": "graph",
   "gridPos": { "h": 9, "w": 9, "x": 15, "y": 29 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "avg(http_requests_current{kubernetes_namespace=~\"$namespace\", kubernetes_pod_name=~\"$pod_name\"}) by (kubernetes_pod_name)",
     "legendFormat": "Concurrent: {{kubernetes_pod_name}}"
    },
    {
     "expr": "avg(rate(http_requests_allowed_total{kubernetes_namespace=~\"$namespace\", kubernetes_pod_name=~\"$pod_name\"}[2m])) by (kubernetes_pod_name)",
     "legendFormat": "Allowed: {{kubernetes_pod_name}}"
    },
    {
     "expr": "avg(rate(http_requests_blocked_total{kubernetes_namespace=~\"$namespace\", kubernetes_pod_name=~\"$pod_name\"}[2m])) by (kubernetes_pod_name)",
     "legendFormat": "Blocked: {{kubernetes_pod_name}}"
    },
    {
     "expr": "avg(rate(http_requests_rejected_total{kubernetes_namespace=~\"$namespace\", kubernetes_pod_name=~\"$pod_name\"}[2m])) by (kubernetes_pod_name)",
     "legendFormat": "Rejected: {{kubernetes_pod_name}}"
    }
   ]
  },
  { "title": "Sessions", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 } },
  {
   "title": "Percentage authenticated sessions by namespace",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_sessions_authenticated_current{kubernetes_namespace=~\"$namespace\", kubernetes_service_name=~\".+\"}[2m])) by (kubernetes_namespace) /\nsum(rate(http_sessions_current{kubernetes_namespace=~\"$namespace\", kubernetes_service_name=~\".+\"}[2m])) by (kubernetes_namespace)",
     "legendFormat": "Authenticated"
    }
   ]
  },
  {
   "title": "Percentage authenticated sessions by service",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 7, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_sessions_authenticated_current{kubernetes_namespace=~\"$namespace\", kubernetes_service_name=~\"$service_name\"}[2m])) by (kubernetes_service_name) /\nsum(rate(http_sessions_current{kubernetes_namespace=~\"$namespace\", kubernetes_service_name=~\"$service_name\"}[2m])) by (kubernetes_service_name)",
     "legendFormat": "{{kubernetes_service_name}}"
    }
   ]
  },
  {
   "title": "Percentage authenticated sessions by pod",
   "type": "graph",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_sessions_authenticated_current{kubernetes_namespace=~\"$namespace\", kubernetes_pod_name=~\"$pod_name\"}[2m])) by (kubernetes_pod_name) /\nsum(rate(http_sessions_current{kubernetes_namespace=~\"$namespace\", kubernetes_pod_name=~\"$pod_name\"}[2m])) by (kubernetes_pod_name)",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Session by namespace",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 47 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "http_sessions_current{kubernetes_namespace=~\"$namespace\", kubernetes_service_name=~\".+\"}",
     "legendFormat": "Concurrent "
    }
   ]
  },
  {
   "title": "Session by service",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 7, "y": 47 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "http_sessions_current{kubernetes_namespace=~\"$namespace\", kubernetes_service_name=~\"$service_name\"}",
     "legendFormat": "Concurrent : {{kubernetes_service_name}}"
    }
   ]
  },
  {
   "title": "Session by pod",
   "type": "graph",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 47 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "http_sessions_current{kubernetes_namespace=~\"$namespace\", kubernetes_pod_name=~\"$pod_name\"}",
     "legendFormat": "Concurrent : {{kubernetes_pod_name}}"
    }
   ]
  },
  { "title": "Timing statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 55 } },
  {
   "title": "Request processing time by namespace",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 56 },
   "yaxes": [
    { "format": "s", "label": "Time" }
   ],
   "targets": [
    {
     "expr": "sum(http_requests_duration_seconds{kubernetes_namespace=~\"$namespace\", kubernetes_service_name=~\".+\"}) by (quantile)",
     "legendFormat": "Percentile {{quantile}}"
    }
   ]
  },
  {
   "title": "Request processing time by service",
   "type": "graph",
   "gridPos": { "h": 10, "w": 11, "x": 0, "y": 65 },
   "yaxes": [
    { "format": "s", "label": "Time" }
   ],
   "targets": [
    {
     "expr": "sum(http_requests_duration_seconds{kubernetes_namespace=~\"$namespace\", kubernetes_service_name=~\"$service_name\"}) by (quantile, kubernetes_service_name)",
     "legendFormat": "{{kubernetes_service_name}}: Percentile {{quantile}}"
    }
   ]
  },
  {
   "title": "Request processing time by pod",
   "type": "graph",
   "gridPos": { "h": 10, "w": 13, "x": 11, "y": 65 },
   "yaxes": [
    { "format": "s", "label": "Time" }
   ],
   "targets": [
    {
     "expr": "sum(http_requests_duration_seconds{kubernetes_namespace=~\"$namespace\", kubernetes_pod_name=~\"$pod_name\"}) by (quantile, kubernetes_pod_name)",
     "legendFormat": "{{kubernetes_pod_name}}: Percentile {{quantile}}"
    }
   ]
  }
 ]
}