  ---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: microgateway-kibana
  labels:
    app: microgateway-kibana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: microgateway-kibana
  template:
    metadata:
      labels:
        app: microgateway-kibana
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9102"
    spec:
      imagePullSecrets:
        - name: dockerregcred
      initContainers:
        - name: configbuilder
          image: docker.io/ergon/airlock-microgateway-configbuilder-nightly:2.1.0.sprint3_Build003
          imagePullPolicy: IfNotPresent
          env:
            - name: TZ
              valueFrom:
                configMapKeyRef:
                  name: generic-parameters
                  key: TZ
            - name: OPERATIONAL_MODE
              value: integration
          volumeMounts:
            - name: config
              mountPath: /config/config.yaml
              subPath: config.yaml
              readOnly: true
            - name: secret
              mountPath: /secret/config/
              readOnly: true
            - name: config-files
              mountPath: /resources-gen
      containers:
        - name: microgateway-kibana
          image: docker.io/ergon/airlock-microgateway-nightly:2.1.0.sprint3_Build003
          imagePullPolicy: IfNotPresent
          env:
            - name: TZ
              valueFrom:
                configMapKeyRef:
                  name: generic-parameters
                  key: TZ
          ports:
            - name: https
              containerPort: 8443
            - name: probes
              containerPort: 9090
            - name: metrics
              containerPort: 9102
          volumeMounts:
            - name: config-files
              mountPath: /config/
          livenessProbe:
            failureThreshold: 9
            timeoutSeconds: 5
            httpGet:
              path: /alive
              port: probes
            initialDelaySeconds: 90
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /healthy
              port: probes
            initialDelaySeconds: 10
          lifecycle:
            preStop:
              exec:
                command:
                  - /usr/bin/sleep
                  - "10"
          resources:
            requests:
              memory: 256Mi
              cpu: 30m
            limits:
              memory: 4048Mi
      volumes:
        - name: config
          configMap:
            name: microgateway-kibana-config
        - name: secret
          secret:
            secretName: microgateway-secret
        - name: config-files
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: microgateway-kibana
  labels:
    app: microgateway-kibana
spec:
  selector:
    app: microgateway-kibana
  ports:
    - name: https
      port: 8443
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: microgateway-kibana-config
data:
  config.yaml: |
    license_file: /secret/config/license

    log:
      level: info

    session:
      redis_hosts: [ redis-master ]
      encryption_passphrase_file: /secret/config/passphrase

    expert_settings:
      apache: |
        RemoteIPHeader x-real-ip
        RemoteIPInternalProxy 10.0.0.0/8
        RemoteIPInternalProxy 172.16.0.0/12
        RemoteIPInternalProxy 192.168.0.0/16
      security_gate: |
        CorrelationId.Extraction.0.Request.Header.Pattern       "^X-Request-ID: ([[:graph:]]+)$"
        CorrelationId.Extraction.0.Request.Header.IgnoreCase    "TRUE"
        CorrelationId.Extraction.0.Request.Header.Template      "$1"

    apps:
      - virtual_host:
          name: vh-kibana
        mappings:
          - name: kibana
            entry_path:
              value: /
            session_handling: enforce_session
            operational_mode: ${OPERATIONAL_MODE:-production}
            deny_rule_groups:
              - level: basic
            limits:
              json_limits:
                max_value_length: 819200
            auth:
              flow: redirect
              denied_access_url: /auth/ui/app/auth/application/access
              access:
                - roles:
                  - authenticated
            backend:
              name: beg-kibana
              hosts:
                - protocol: 'http'
                  name: kibana
                  port: 5601
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-microgateway-kibana
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: https
spec:
  rules:
    - http:
        paths:
          - path: /kibana/
            pathType: Prefix
            backend:
              service:
                name: microgateway-kibana
                port:
                  number: 8443
