---
apiVersion: v1
kind: ConfigMap
metadata:
  name: echoserver-config
  annotations:
    helm.sh/hook: pre-install
    helm.sh/hook-weight: "-90"
data:
  {{ (.Files.Glob "config/nginx/*").AsConfig | nindent 2 }}
