---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: echoserver-microgateway
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: "{{ .Values.echoserver.microgateway.spec.source.repoURL }}"
    targetRevision: "{{ .Values.echoserver.microgateway.spec.source.targetRevision }}"
    chart: "{{ .Values.echoserver.microgateway.spec.source.chart }}"

    helm:
      values: |
        image:
          tag: "3.1"

        fullnameOverride: echoserver-microgateway

        resources:
          limits:
            memory: 512Mi

        podAnnotations:
          prometheus.io/scrape: "true"
          prometheus.io/port: "9102"

        service:
          annotations:
            prometheus.io/scrape: "true"
            prometheus.io/port: "9102"

        ingress:
          enabled: true
          annotations:
            kubernetes.io/ingress.class: "nginx"
            nginx.ingress.kubernetes.io/backend-protocol: https
            nginx.ingress.kubernetes.io/rewrite-target: /echo/
          path: /echo/
          pathType: Prefix
          servicePortName: https

        config:
          passphrase:
            useExistingSecret: true
            secretName: microgateway-passphrase

          {{- if .Values.microgateway.license.secretName }}
          license:
            useExistingSecret: true
            secretName: {{ .Values.microgateway.license.secretName }}
          {{- end }}

          {{- if .Values.authentication.enabled }}
          env:
            configbuilder:
              - name: JWT_ENCRYPTION_PASSPHRASE
                valueFrom:
                  secretKeyRef:
                    name: jwt-secret
                    key: JWT_ENCRYPTION_PASSPHRASE
              - name: JWT_SIGNATURE_PASSPHRASE
                valueFrom:
                  secretKeyRef:
                    name: jwt-secret
                    key: JWT_SIGNATURE_PASSPHRASE
              - name: COOKIE_NAME
                valueFrom:
                  secretKeyRef:
                    name: jwt-secret
                    key: COOKIE_NAME
          {{- end }}

          dslConfigMap: echoserver-microgateway-config

  destination:
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy: {{ toYaml .Values.spec.syncPolicy | nindent 4 }}
