grafana:
  microgateway:
    spec:
      source:
        repoURL: https://ergon.github.io/airlock-helm-charts
        targetRevision: 3.0.4
        chart: microgateway

    helm:
      values:
        image:
          tag: "3.1"

        fullnameOverride: grafana-microgateway

        resources:
          limits:
            memory: 512Mi

        podAnnotations:
          prometheus.io/scrape: "true"
          prometheus.io/port: "9102"

        service:
          annotations:
            prometheus.io/scrape: "true"
            prometheus.io/port: "9102"

        ingress:
          enabled: true
          annotations:
            kubernetes.io/ingress.class: "nginx"
            nginx.ingress.kubernetes.io/backend-protocol: https
            nginx.ingress.kubernetes.io/rewrite-target: $1
          path: (/grafana/.*)
          pathType: Prefix
          servicePortName: https

        config:
          passphrase:
            useExistingSecret: true
            secretName: microgateway-passphrase
