prometheus:
  spec:
    source:
      repoURL: https://prometheus-community.github.io/helm-charts
      targetRevision: 14.3.0
      chart: prometheus

  helm:
    values:
      imagePullSecrets:
        - name: dockerregcred

      alertmanager:
        enabled: false
      alertmanagerFiles:
        alertmanager.yml: ""
      kubeStateMetrics:
        enabled: false
      nodeExporter:
        enabled: false
      pushgateway:
        enabled: false

      server:
        persistentVolume:
          size: 100M
