grafana:
  microgateway:
    resources:
      path: data/monitoring/microgateway-with-iam/
    helm:
      values:
        config:
          env:
            configbuilder:
              - name: LOG_LEVEL
                value: info
              - name: OPERATIONAL_MODE
                value: production

          dslConfigMap: grafana-microgateway-config
