echoserver:
  microgateway:
    helm:
      values:
        config:
          env:
            configbuilder:
              - name: LOG_LEVEL
                value: info
              - name: OPERATIONAL_MODE
                value: integration
              - name: ACCESS_ROLES
                value: [{ "roles": ["echo-user"] }]
              - name: JWT_ENCRYPTION_PASSPHRASE
                valueFrom:
                  secretKeyRef:
                    name: jwt-secret
                    key: JWT_ENCRYPTION_PASSPHRASE
              - name: JWT_SIGNATURE_PASSPHRASE
                valueFrom:
                  secretKeyRef:
                    name: jwt-secret
                    key: JWT_SIGNATURE_PASSPHRASE
              - name: COOKIE_NAME
                valueFrom:
                  secretKeyRef:
                    name: jwt-secret
                    key: COOKIE_NAME

          dslConfigMap: echoserver-microgateway-config
