echoserver:
  microgateway:
    resources:
      path: data/backend/microgateway-without-iam/
    helm:
      values:
        config:
          env:
            configbuilder:
              - name: LOG_LEVEL
                value: info
              - name: OPERATIONAL_MODE
                value: integration

          dslConfigMap: echoserver-microgateway-config
