echoserver:
  microgateway:
    resources:
      path: data/backend/microgateway-with-iam/
    helm:
      values:
        config:
          env:
            configbuilder:
              - name: JWT_ENCRYPTION_PASSPHRASE
                valueFrom:
                  secretKeyRef:
                    name: jwt-secret
                    key: JWT_ENCRYPTION_PASSPHRASE
              - name: JWT_SIGNATURE_PASSPHRASE
                valueFrom:
                  secretKeyRef:
                    name: jwt-secret
                    key: JWT_SIGNATURE_PASSPHRASE
              - name: COOKIE_NAME
                valueFrom:
                  secretKeyRef:
                    name: jwt-secret
                    key: COOKIE_NAME

          dslConfigMap: echoserver-microgateway-config
