echoserver:
  microgateway:
    helm:
      values:
        config:
          env:
            configbuilder:
              - name: LOG_LEVEL
                value: info
              - name: OPERATIONAL_MODE
                value: integration

          dsl:
            log:
              level: ${LOG_LEVEL:-info}

            remote_ip:
              header: x-real-ip
              internal_proxies:
                - 10.0.0.0/8
                - 172.16.0.0/12
                - 192.168.0.0/16

            expert_settings:
              security_gate: |
                CorrelationId.Extraction.0.Request.Header.Pattern       "^X-Request-ID: ([[:graph:]]+)$"
                CorrelationId.Extraction.0.Request.Header.IgnoreCase    "TRUE"
                CorrelationId.Extraction.0.Request.Header.Template      "$1"

            apps:
              - virtual_host:
                  name: vh-echoserver
                mappings:
                  - name: echoserver
                    entry_path:
                      value: /echo/
                    session_handling: ignore_session
                    operational_mode: ${OPERATIONAL_MODE:-production}
                    threat_handling: block
                    deny_rule_groups:
                      - level: strict
                    expert_settings:
                      security_gate: |
                        Backend.AddEnvironmentCookies         "TRUE"
                    backend:
                      name: beg-echoserver
                      hosts:
                        - protocol: "http"
                          name: echoserver
                          port: 8080
