echoserver:
  microgateway:
    spec:
      source:
        repoURL: https://ergon.github.io/airlock-helm-charts
        targetRevision: 3.0.4
        chart: microgateway

    helm:
      values:
        image:
          tag: "3.1"

        fullnameOverride: echoserver-microgateway

        resources:
          limits:
            memory: 512Mi

        podAnnotations:
          prometheus.io/scrape: "true"
          prometheus.io/port: "9102"

        service:
          annotations:
            prometheus.io/scrape: "true"
            prometheus.io/port: "9102"

        config:
          passphrase:
            useExistingSecret: true
            secretName: microgateway-passphrase
