---
config:
  target: https://ingress-nginx-controller.ingress-nginx
  tls:
    rejectUnauthorized: false
  plugins:
    expect: {}
  phases:
    # Ramp up: From 1 VU to 5 VU over 45 seconds
    - name: "Warm up the application"
      duration: 45
      arrivalRate: 1
      rampTo: 5
    - name: "Sustained max load"
      duration: 1200
      arrivalRate: 1
      rampTo: 5
  variables:
    username:
      - customer1
      - customer2
      - customer3
      - customer4
      - customer5
    user-agents:
      - Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.169 Safari/537.36
      - Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36
      - Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3198.0 Safari/537.36 OPR/49.0.2711.0
      - Mozilla/5.0 (Windows NT 5.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36 OPR/43.0.2442.991
      - Mozilla/5.0 (X11; Ubuntu; Linux i686; rv:24.0) Gecko/20100101 Firefox/24.0
      - Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.121 Safari/537.36
      - Mozilla/5.0 (Linux; U; Android 2.2) AppleWebKit/533.1 (KHTML, like Gecko) Version/4.0 Mobile Safari/533.1
      - Mozilla/5.0 (Linux; Android 6.0.1; SM-G532G Build/MMB29T) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.83 Mobile Safari/537.36
      - Mozilla/5.0 (Linux; Android 8.0.0; SM-G960F Build/R16NW) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.84 Mobile Safari/537.36
      - Mozilla/5.0 (iPhone; CPU iPhone OS 12_0 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) CriOS/69.0.3497.105 Mobile/15E148 Safari/605.1
      - Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.135 Safari/537.36 Edge/12.10532
      - Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; BOIE9;ENUSMSE; rv:11.0) like Gecko
      - Mozilla/5.0 (Windows NT 6.2; WOW64; rv:29.0) Gecko/20100101 Firefox/29.0
      - Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 6.1; WOW64; Trident/4.0; SLCC2; .NET CLR 2.0.50727; .NET CLR 3.5.30729; .NET CLR 3.0.30729; .NET4.0C; .NET4.0E; InfoPath.3)
      - Mozilla/5.0 (Windows NT 6.1; WOW64; rv:29.0) Gecko/20100101 Firefox/29.0
      - Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 6.1; Trident/4.0; SLCC2; .NET CLR 2.0.50727; .NET CLR 3.5.30729; .NET CLR 3.0.30729; Media Center PC 6.0; .NET4.0C; .NET4.0E; InfoPath.3)
      - Mozilla/5.0 (Linux; Android 4.4.2; SM-T320 Build/KOT49H) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.84 Safari/537.36
      - Mozilla/5.0 (iPad; CPU OS 8_4 like Mac OS X) AppleWebKit/600.1.4 (KHTML, like Gecko) CriOS/44.0.2403.67 Mobile/12H143 Safari/600.1.4
      - Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/36.0.1985.143 Safari/537.36
      - Mozilla/5.0 (iPhone; CPU iPhone OS 8_4_1 like Mac OS X) AppleWebKit/600.1.4 (KHTML, like Gecko) GSA/7.0.55539 Mobile/12H321 Safari/600.1.4
      - Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/44.0.2403.130 Safari/537.36
    X-Forwarded-For:
      # https://lite.ip2location.com/ip-address-ranges-by-country
      # Brazil
      - 103.4.98.225
      - 103.4.98.230
      # USA
      - 102.140.88.1
      - 102.140.88.3
      - 102.140.88.7
      # Germany
      - 102.165.8.1
      - 102.165.8.3
      - 102.165.8.14
      # Switzerland
      - 104.132.24.1
      - 104.132.24.5
      - 104.132.24.18
      # France
      - 103.153.7.1
      - 103.153.7.5
      - 103.153.7.19
      # Denmark
      - 104.160.16.1
      - 104.160.16.5
      - 104.160.16.9
      # Croatia
      - 130.176.45.1
      - 130.176.45.5
      # Sweden
      - 104.123.68.1
      - 104.123.68.6
      # China
      - 1.2.0.1
      - 1.2.0.2
    attack-strings:
      - 1=1--
      - <script>onclick('xss')</script>
      - <img src='https://www.evil.com/script.js'>
      - ../etc/passwd
scenarios:
  - name: "Authenticated session with some requests"
    flow:
      - log: "Authenticate user's session and send some requests"
      - post:
          url: "/auth/rest/public/authentication/location/access"
          headers:
            User-Agent: "{{ user-agents }}"
            X-Forwarded-For: "{{ X-Forwarded-For }}"
            X-Same-Domain: "1"
          json:
            location: "https://ingress-nginx-controller.ingress-nginx/echo/"
          expect:
            - statusCode: 401
      - think: 4
      - post:
          url: "/auth/rest/public/authentication/password/check"
          headers:
            User-Agent: "{{ user-agents }}"
            X-Forwarded-For: "{{ X-Forwarded-For }}"
            X-Same-Domain: "1"
          json:
            username: "{{ username }}"
            password: password
          expect:
            - statusCode: 200
      - think: 4
      - get:
          url: "/echo/users/{{ $randomNumber(1, 100) }}"
          headers:
            User-Agent: "{{ user-agents }}"
            X-Forwarded-For: "{{ X-Forwarded-For }}"
          expect:
            - statusCode: 200
      - think: 4
      - post:
          url: "/echo/users/create/"
          headers:
            User-Agent: "{{ user-agents }}"
            X-Forwarded-For: "{{ X-Forwarded-For }}"
            Content-Type: application/json
          json:
            username: "{{ $randomString(5) }}"
          expect:
            - statusCode: 200
      - think: 4
      - get:
          url: "/echo/?sleep=y"
          headers:
            User-Agent: "{{ user-agents }}"
            X-Forwarded-For: "{{ X-Forwarded-For }}"
          expect:
            - statusCode: 204
      - think: 4
      - get:
          url: "/echo/?code=204"
          headers:
            User-Agent: "{{ user-agents }}"
            X-Forwarded-For: "{{ X-Forwarded-For }}"
          expect:
            - statusCode: 204
      - think: 4
      - get:
          url: "/echo/?code=403"
          headers:
            User-Agent: "{{ user-agents }}"
            X-Forwarded-For: "{{ X-Forwarded-For }}"
          expect:
            - statusCode: 403
      - think: 4
      - get:
          url: "/echo/?code=503"
          headers:
            User-Agent: "{{ user-agents }}"
            X-Forwarded-For: "{{ X-Forwarded-For }}"
          expect:
            - statusCode: 503
      - think: 4
      - get:
          url: "/auth/logout"
          headers:
            User-Agent: "{{ user-agents }}"
            X-Forwarded-For: "{{ X-Forwarded-For }}"
          expect:
            - statusCode: 302
    weight: 7
  - name: "Attack string"
    flow:
      - log: "Attack string"
      - get:
          url: "/echo/"
          headers:
            User-Agent: "{{ user-agents }}"
            X-Forwarded-For: "{{ X-Forwarded-For }}"
            X-Attack: "{{ attack-strings }}"
          expect:
            - statusCode: 400
      - think: 4
      - get:
          url: "/echo/"
          headers:
            User-Agent: "{{ user-agents }}"
            X-Forwarded-For: "{{ X-Forwarded-For }}"
            X-Attack: "{{ attack-strings }}"
          expect:
            - statusCode: 400
      - think: 4
      - get:
          url: "/echo/?q=<img src='https://www.evil.com/script.js'>"
          headers:
            User-Agent: "{{ user-agents }}"
            X-Forwarded-For: "{{ X-Forwarded-For }}"
          expect:
            - statusCode: 400
      - think: 4
      - get:
          url: "/auth/login/?file={{ attack-strings }}"
          headers:
            User-Agent: "{{ user-agents }}"
            X-Forwarded-For: "{{ X-Forwarded-For }}"
          expect:
            - statusCode: 400
    weight: 2
  - name: "Parameter tampering"
    flow:
      - log: "Parameter tampering"
      - post:
          url: "/auth/login"
          headers:
            User-Agent: "{{ user-agents }}"
            X-Forwarded-For: "{{ X-Forwarded-For }}"
            Content-Type: application/json
          json:
            user: "{{ username }}"
            password: password
          expect:
            - statusCode: 400
    weight: 1
