---
{{- if .Values.authentication.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: authentication
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: "{{ .Values.spec.source.repoURL }}"
    targetRevision: "{{ .Values.spec.source.targetRevision }}"
    path: apps/authentication/

    helm:
      values: |
        spec:
          source:
            repoURL: "{{ .Values.spec.source.repoURL }}"
            targetRevision: "{{ .Values.spec.source.targetRevision }}"

          syncPolicy: {{ toYaml .Values.spec.syncPolicy | nindent 12 }}

        microgateway:
          license:
            secretName: {{ .Values.microgateway.license.secretName }}
  destination:
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy: {{ toYaml .Values.spec.syncPolicy | nindent 4 }}
{{- end }}
