{{- if .Values.authentication.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: authentication
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: "{{ .Values.spec.source.repoURL }}"
    targetRevision: "{{ .Values.spec.source.targetRevision }}"
    path: apps/authentication/

    helm:
      valueFiles:
        - values-iam.yaml
        - values-iam-microgateway.yaml
        - values-mariadb.yaml

      values: |
        example:
          repoURL: "{{ .Values.spec.source.repoURL }}"
          targetRevision: "{{ .Values.spec.source.targetRevision }}"

  destination:
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy: {{ toYaml .Values.spec.syncPolicy | nindent 4 }}
{{- end }}