---
{{- if .Values.backend.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: backend
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: "{{ .Values.spec.source.repoURL }}"
    targetRevision: "{{ .Values.spec.source.targetRevision }}"
    path: apps/backend/

    helm:
      values: |
        spec:
          syncPolicy: {{ toYaml .Values.spec.syncPolicy | nindent 12 }}

        authentication:
          enabled: "{{ .Values.authentication.enabled }}"

        microgateway:
          license:
            secretName: "{{ .Values.microgateway.license.secretName }}"

  destination:
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy: "{{ toYaml .Values.spec.syncPolicy | nindent 4 }}"
{{- end }}