{{- if .Values.logging.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: logging
  namespace: argocd
  annotations:
    helm.sh/hook: pre-install
    helm.sh/hook-weight: "-70"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: "{{ .Values.spec.source.repoURL }}"
    targetRevision: "{{ .Values.spec.source.targetRevision }}"
    path: apps/logging/

    helm:
      valueFiles:
        - values-elasticsearch.yaml
        - values-kibana.yaml

      values: |
        spec:
          source:
            repoURL: "{{ .Values.spec.source.repoURL }}"
            targetRevision: "{{ .Values.spec.source.targetRevision }}"

          syncPolicy: {{ toYaml .Values.spec.syncPolicy | nindent 12 }}

        authentication:
          enabled: {{ .Values.authentication.enabled }}

        microgateway:
          license:
            secretName: {{ .Values.microgateway.license.secretName }}

  destination:
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy: {{ toYaml .Values.spec.syncPolicy | nindent 4 }}
{{- end }}