apiVersion: v1
kind: Secret
metadata:
  name: microgateway-passphrase
  annotations:
    helm.sh/hook: pre-install
    helm.sh/hook-weight: "-90"
type: Opaque
stringData:
  passphrase: {{ randAlphaNum 128 | quote }}
