{{- if .Values.monitoring.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring
  namespace: argocd
  annotations:
    helm.sh/hook: pre-install
    helm.sh/hook-weight: "-60"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: "{{ .Values.spec.source.repoURL }}"
    targetRevision: "{{ .Values.spec.source.targetRevision }}"
    path: apps/monitoring/

    helm:
      valueFiles:
        - values-prometheus.yaml
        - values-grafana.yaml
        - values-grafana-microgateway.yaml
        {{- if .Values.authentication.enabled }}
        - values-microgateway-config-with-iam.yaml
        {{- else }}
        - values-microgateway-config-without-iam.yaml
        {{- end }}
        {{- if .Values.microgateway.license.secretName }}
        - values-microgateway-with-license.yaml
        {{- end }}

      values: |
        example:
          repoURL: "{{ .Values.spec.source.repoURL }}"
          targetRevision: "{{ .Values.spec.source.targetRevision }}"

        spec:
          syncPolicy: {{ toYaml .Values.spec.syncPolicy | nindent 12 }}

  destination:
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy: {{ toYaml .Values.spec.syncPolicy | nindent 4 }}
{{- end }}