apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: redis
  namespace: argocd
  annotations:
    helm.sh/hook: pre-install
    helm.sh/hook-weight: "-50"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 10.6.12
    chart: redis

    helm:
      values: |
        fullnameOverride: redis
        securityContext:
          enabled: false
        cluster:
          enabled: false
        usePassword: false
        master:
          disableCommands: []
          persistence:
            enabled: false

  destination:
    server: https://kubernetes.default.svc
    namespace: default

  "{{ .Values.spec.syncPolicy }}"
