---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: redis
  namespace: argocd
  annotations:
    helm.sh/hook: pre-install
    helm.sh/hook-weight: "-50"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 15.7.6
    chart: redis

    helm:
      values: |
        fullnameOverride: redis
        architecture: standalone
        auth:
          enabled: false
        master:
          containerSecurityContext:
            enabled: false
          disableCommands: []
          # do not disable any commands since Microgateway needs full control
          # to configure the redis session store.
          persistence:
            enabled: false
        replica:
          containerSecurityContext:
            enabled: false
        metrics:
          containerSecurityContext:
            enabled: false

  destination:
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy: {{ toYaml .Values.spec.syncPolicy | nindent 4 }}
