---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: microgateway-kibana
  labels:
    app: microgateway-kibana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: microgateway-kibana
  template:
    metadata:
      labels:
        app: microgateway-kibana
    spec:
      imagePullSecrets:
        - name: dockerregcred
      containers:
      - name: microgateway-kibana
        image: ergon/airlock-microgateway:1.0
        imagePullPolicy: IfNotPresent
        env:
        - name: TZ
          valueFrom:
            configMapKeyRef:
              name: generic-parameters
              key: TZ
        - name: ALG_CFG_OPERATIONAL_MODE
          value: production
        ports:
        - name: https
          containerPort: 8443
        volumeMounts:
        - name: config
          mountPath: /config/config.yaml
          subPath: config.yaml
        - name: secret
          mountPath: /secret/config/
          readOnly: true
        livenessProbe:
          httpGet:
            path: /healthz
            port: https
            scheme: HTTPS
          initialDelaySeconds: 90
        readinessProbe:
          httpGet:
            path: /healthz
            port: https
            scheme: HTTPS
          initialDelaySeconds: 30
      volumes:
      - name: config
        configMap:
          name: microgateway-kibana-config
      - name: secret
        secret:
          secretName: microgateway-secrets
---
apiVersion: v1
kind: Service
metadata:
  name: microgateway-kibana
  labels:
    app: microgateway-kibana
spec:
  selector:
    app: microgateway-kibana
  ports:
    - name: https
      port: 8443
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: microgateway-kibana-config
data:
  config.yaml: |
    license_file: /secret/config/license

    log:
      level: info
    
    session:
      redis_hosts:
      - 'redis:6379'
      store_mode: server
      encryption_passphrase_file: /secret/config/passphrase

    expert_settings:
      apache: |
        RemoteIPHeader x-real-ip
        RemoteIPInternalProxy 10.0.0.0/8
        RemoteIPInternalProxy 172.16.0.0/12
        RemoteIPInternalProxy 192.168.0.0/16
      security_gate: |
        # TODO:
        # Needed until AP-21937 is available.
        # Attention: Request Header Whitelist must allow this header
        Request.Logging.Headers.Enable        "TRUE"
        Request.Logging.Headers.Mode          "request"
        Request.Logging.Headers.Pattern       "^x-request-id:"
        Request.Logging.Headers.IgnoreCase    "TRUE"
        Request.Logging.Headers.InvertPattern "FALSE"
    
    apps:
    - virtual_host:
        name: vh-kibana
      mappings:
      - name: kibana
        entry_path: /
        session_handling: enforce_session
        operational_mode: @@ALG_CFG_OPERATIONAL_MODE@@
        deny_rules:
        - level: basic
        limits:
          json_limits:
            max_value_length: 819200
        auth:
          flow: redirect
          denied_access_url: /auth/check-login
          access:
          - roles:
            - authenticated
      backend:
        name: beg-kibana
        protocol: 'http'
        hostname: kibana
        port: 5601
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-microgateway-kibana
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: https
spec:
  rules:
  - http:
      paths:
      - path: /kibana
        pathType: Prefix
        backend:
          service:
            name: microgateway-kibana
            port: 
              number: 8443