---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: echoserver
  labels:
    app: echoserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: echoserver
  template:
    metadata:
      labels:
        app: echoserver
    spec:
      containers:
      - name: echoserver
        image: openresty/openresty:1.19.3.1-alpine
        imagePullPolicy: IfNotPresent
        env:
        - name: TZ
          valueFrom:
            configMapKeyRef:
              name: generic-parameters
              key: TZ
        ports:
        - name: http
          containerPort: 8080
        volumeMounts:
        - name: config
          mountPath: /usr/local/openresty/nginx/conf/nginx.conf
          subPath: nginx.conf
      volumes:
      - name: config
        configMap:
          name: echoserver-nginx-config
---
apiVersion: v1
kind: Service
metadata:
  name: echoserver
  labels:
    app: echoserver
spec:
  selector:
    app: echoserver
  ports:
    - name: http
      port: 8080
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: echoserver-nginx-config
data:
  nginx.conf : |
    error_log  /dev/stderr debug;

    events {
        worker_connections  1024;
    }


    http {
        log_format main escape=json '{'
        '"timestamp": "$time_iso8601",  '
        '"req_id": "$request_id", '
        '"upstream_status": "$upstream_status", '
        '"upstream_addr": "$upstream_addr", '
        '"http_req":{ '
        '  "http_method": "$request_method", '
        '  "entry_url": "$scheme://$host$request_uri", '
        '  "entry_path": "$request_uri", '
        '  "entry_query": "$query_string", '
        '  "http_status": $status, '
        '  "vhost_proto":"$scheme", '
        '  "vhost_proto_vers": "$server_protocol", '
        '  "http_user_agent": "$http_user_agent", '
        '  "http_referrer": "$http_referer", '
        '  "http_content_type": "$content_type", '
        '  "http_host": "$host", '
        '  "http_x_request_id": "$http_x_request_id", '
        '  "req_size": "$request_length", '
        '  "resp_size": "$upstream_response_length", '
        '  "time_resp": "$upstream_response_time s", '
        '  "client_ip": "$remote_addr", '
        '  "front_src_ip": "$http_x_forwarded_for", '
        '  "front_src_port": "$remote_port", '
        '  "front_dst_port": "$server_port", '
        '  "front_tls_proto": "$ssl_protocol", '
        '  "front_tls_cipher": "$ssl_cipher" '
        '}}';
        access_log /dev/stdout main;
        include mime.types;

        server {
            listen       8080;
            
            location / {
              echo_duplicate 1 $echo_client_request_headers;
              echo "\r";
              echo_read_request_body;
              echo $request_body;
            }
        }
    }