---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: artillery
  labels:
    app: artillery
spec:
  replicas: 1
  selector:
    matchLabels:
      app: artillery
  template:
    metadata:
      labels:
        app: artillery
    spec:
      imagePullSecrets:
        - name: dockerregcred
      containers:
        - name: artillery
          image: docker.io/artilleryio/artillery:v1.7.9
          imagePullPolicy: IfNotPresent
          args: ["run", "/config/artillery.yaml"]
          # env:
          #   - name: "DEBUG"
          #     value: "http"
          volumeMounts:
            - name: config
              mountPath: /config/
      volumes:
        - name: config
          configMap:
            name: artillery-config
