---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

commonLabels:
  app: argo

resources:
  - ns.yaml
  - github.com/argoproj/argo-cd/manifests/crds/?ref=v2.0.5
  - github.com/argoproj/argo-cd/manifests/cluster-rbac/?ref=v2.0.5
  - github.com/argoproj/argo-cd/manifests/base/application-controller/?ref=v2.0.5
  - github.com/argoproj/argo-cd/manifests/base/config/?ref=v2.0.5
  - github.com/argoproj/argo-cd/manifests/base/redis/?ref=v2.0.5
  - github.com/argoproj/argo-cd/manifests/base/repo-server/?ref=v2.0.5
  - github.com/argoproj/argo-cd/manifests/base/server/?ref=v2.0.5

images:
  - name: quay.io/argoproj/argocd
    newName: quay.io/argoproj/argocd
    newTag: v2.0.5

patchesStrategicMerge:
  - set_image_pull_secrets.yaml
