---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-redis
spec:
  template:
    spec:
      imagePullSecrets:
        - name: dockerregcred
      containers:
        - name: redis
          imagePullPolicy: IfNotPresent
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-repo-server
spec:
  template:
    spec:
      imagePullSecrets:
        - name: dockerregcred
      containers:
        - name: argocd-repo-server
          imagePullPolicy: IfNotPresent
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-server
spec:
  template:
    spec:
      imagePullSecrets:
        - name: dockerregcred
      containers:
        - name: argocd-server
          imagePullPolicy: IfNotPresent
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: argocd-application-controller
spec:
  template:
    spec:
      imagePullSecrets:
        - name: dockerregcred
      containers:
        - name: argocd-application-controller
          imagePullPolicy: IfNotPresent
