apiVersion: v1
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"hsts":"false"},"kind":"ConfigMap","metadata":{"annotations":{},"labels":{"addonmanager.kubernetes.io/mode":"EnsureExists"},"name":"nginx-load-balancer-conf","namespace":"kube-system"}}
  labels:
    addonmanager.kubernetes.io/mode: EnsureExists
  name: nginx-load-balancer-conf
  namespace: kube-system
data:
  hsts: "false"
  use-forwarded-headers: "true"