---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: iam
  labels:
    app: iam
spec:
  replicas: 1
  selector:
    matchLabels:
      app: iam
  template:
    metadata:
      labels:
        app: iam
    spec:
      imagePullSecrets:
      - name: dockerregcred
      initContainers:
      - name: iam-bootstrap
        image: busybox
        imagePullPolicy: IfNotPresent
        env:
        - name: TZ
          valueFrom:
            configMapKeyRef:
              name: generic-parameters
              key: TZ
        - name: MARIADB_SERVICE
          value: mariadb
        - name: MYSQL_DATABASE
          valueFrom:
            secretKeyRef:
              name: mariadb-secrets
              key: MYSQL_DATABASE
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: mariadb-secrets
              key: MYSQL_USER
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mariadb-secrets
              key: MYSQL_PASSWORD
        command:
        - sh
        - "-c"
        - |
          echo "- Replacing the placeholders in the IAM configuration"
          sed -i "s,@@DB_SERVICE@@,${MARIADB_SERVICE},;\
            s,@@DB_IAM@@,${MYSQL_DATABASE},; \
            s,@@DB_USER@@,${MYSQL_USER},;\
            s,@@DB_PASSWORD@@,${MYSQL_PASSWORD}," \
            /home/airlock/iam/instances/auth/medusa-configuration.xml
        volumeMounts:
        - name: data
          mountPath: /home/airlock/iam/
          subPath: iam
      containers:
      - name: iam
        image: ergon/airlock-iam:latest-7.3
        imagePullPolicy: IfNotPresent
        env:
        - name: TZ
          valueFrom:
            configMapKeyRef:
              name: generic-parameters
              key: TZ
        - name: IAM_LOG_LEVEL
          value: DEBUG
        ports:
        - name: https
          containerPort: 8443
        volumeMounts:
        - name: data
          mountPath: /home/airlock/iam/
          subPath: iam
        - name: secret
          mountPath: /home/airlock/iam/license.txt
          subPath: license.txt
        # TODO:
        # livenessProbe:
        #   httpGet:
        #     path: /health
        #     port: https
        #     scheme: HTTPS
        #   initialDelaySeconds: 60
        # readinessProbe:
        #   httpGet:
        #     path: /auth-login/health
        #     port: https
        #     scheme: HTTPS
        #   initialDelaySeconds: 120
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: data-claim
      - name: secret
        secret:
          secretName: iam-secrets
---
apiVersion: v1
kind: Service
metadata:
  name: iam
  labels:
    app: iam
spec:
  selector:
    app: iam
  ports:
  - name: https
    port: 8443