apiVersion: apps/v1
kind: Deployment
metadata:
  name: iam
  labels:
    app: iam
spec:
  replicas: 1
  selector:
    matchLabels:
      app: iam
  template:
    metadata:
      labels:
        app: iam
    spec:
      imagePullSecrets:
      - name: dockerregcred
      initContainers:
      - name: git-sync
        image: k8s.gcr.io/git-sync/git-sync:v3.2.0
        imagePullPolicy: IfNotPresent
        env:
        - name: GIT_SYNC_REPO
          value: https://github.com/ergon/airlock-minikube-examples.git
          # TODO: Change before merge
        - name: GIT_SYNC_BRANCH
          value: iam
        - name: GIT_SYNC_ROOT
          value: /var/tmp/gitsync/
        - name: GIT_SYNC_DEST
          value: tmp
        - name: GIT_SYNC_SUBMODULES
          value: "off"
        - name: GIT_SYNC_ONE_TIME
          value: "true"
        volumeMounts:
        - name: config
          mountPath: /home/airlock/iam/
      - name: copy-sql-files
        image: busybox
        command:
        - sh
        - "-c"
        - |
          ls -la /var/tmp/gitsync/tmp/iam/ && \
          cp -rp /var/tmp/gitsync/tmp/iam/data/iam/ /home/airlock/iam/ && \
          cp /var/tmp/iam/license.txt /home/airlock/iam/ && \
          ls -la /home/airlock/iam/
        volumeMounts:
        - name: config
          mountPath: /home/airlock/iam/
        - name: secret
          mountPath: /var/tmp/iam/license.txt
          subPath: license.txt
      containers:
      - name: iam
        image: ergon/airlock-iam:latest-7.3
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 8080
        - name: https
          containerPort: 8443
        volumeMounts:
        - name: config
          mountPath: /home/airlock/iam/
        - name: secret
          mountPath: /home/airlock/iam/license.txt
          subPath: license.txt
        livenessProbe:
          httpGet:
            path: /health
            port: https
        readinessProbe:
          httpGet:
            path: /auth-login/health
            port: https
      volumes:
      - name: config
        persistentVolumeClaim:
          claimName: iam-pv-claim
      - name: secret
        secret:
          secretName: iam-secrets      