kibana:
  microgateway:
    helm:
      values:
        config:
          env:
            configbuilder:
              - name: LOG_LEVEL
                value: info
              - name: OPERATIONAL_MODE
                value: production

          dslConfigMap: kibana-microgateway-without-iam-config
