kibana:
  microgateway:
    resources:
      path: data/logging/microgateway-without-iam/
    helm:
      values:
        config:
          env:
            configbuilder:
              - name: LOG_LEVEL
                value: info
              - name: OPERATIONAL_MODE
                value: production

          dslConfigMap: kibana-microgateway-config
