---
apiVersion: v1
kind: ConfigMap
metadata:
  name: elasticsearch-airlock-reporting-bundle
  annotations:
    helm.sh/hook: pre-install
    helm.sh/hook-weight: "-90"
data:
  {{ (.Files.Glob "config/elasticsearch/*").AsConfig | nindent 2 }}
