---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fluentd
  namespace: argocd
  annotations:
    helm.sh/hook-weight: "-5"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 5.0.21
    chart: fluentd

    helm:
      values: |
        aggregator:
          enabled: false

        forwarder:
          configMap: fluentd-forwarder
          extraEnv:
            - name: FLUENTD_DAEMON_USER
              value: root
            - name: FLUENTD_DAEMON_GROUP
              value: root

  destination:
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy: {{ toYaml .Values.spec.syncPolicy | nindent 4 }}
