---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kibana
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://helm.elastic.co
    targetRevision: 7.14.0
    chart: kibana

    helm:
      values: |
        # The newer Helm chart is required to use "extraVolumes" and "extraVolumeMounts"
        imageTag: 7.8.1

        extraEnvs:
          - name: "SERVER_BASEPATH"
            value: "/kibana"
          - name: "SERVER_REWRITEBASEPATH"
            value: "true"

        healthCheckPath: "${SERVER_BASEPATH}/app/kibana"

  destination:
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy: {{ toYaml .Values.spec.syncPolicy | nindent 4 }}
