---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kibana-microgateway-config
  annotations:
    helm.sh/hook: pre-install
    helm.sh/hook-weight: "-90"
data:
  {{ (.Files.Glob "config/microgateway/config.yaml").AsConfig | nindent 2 }}
