apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: iam
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: "{{ .Values.example.repoURL }}"
    targetRevision: "{{ .Values.example.targetRevision }}"
    path: "{{ .Values.iam.resources.path }}"

  destination:
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    {{ toYaml .Values.spec.syncPolicy | nindent 4 }}
    syncOptions:
      - Replace=true
