---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mariadb
  namespace: argocd
  annotations:
    helm.sh/hook-weight: "-10"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 11.1.7
    chart: mariadb

    helm:
      values: |
        initdbScriptsConfigMap: iam-mariadb-sql-files
        primary:
          persistence:
            size: 100M

        auth:
          database: iamdb
          username: airlock
          existingSecret: mariadb-secret

  destination:
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy: {{ toYaml .Values.spec.syncPolicy | nindent 4 }}
