---
apiVersion: v1
kind: Secret
metadata:
  name: mariadb-secret
  annotations:
    helm.sh/hook: pre-install
    helm.sh/hook-weight: "-90"
type: Opaque
stringData:
  mariadb-root-password: "{{ randAlphaNum 36 | b64enc }}"
  mariadb-password: "{{ randAlphaNum 36 | b64enc }}"
  mariadb-replication-password: "{{ randAlphaNum 36 | b64enc }}"
