---
apiVersion: v1
kind: ConfigMap
metadata:
  name: iam-mariadb-sql-files
  annotations:
    helm.sh/hook: pre-install
    helm.sh/hook-weight: "-90"
data:
  {{ (.Files.Glob "config/mariadb/*").AsConfig | nindent 2 }}
