---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: iam-microgateway-files
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
spec:
  project: default
  source:
    repoURL: "{{ .Values.spec.source.repoURL }}"
    targetRevision: "{{ .Values.spec.source.targetRevision }}"
    path: data/authentication/microgateway/

  destination:
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    {{ toYaml .Values.spec.syncPolicy | nindent 4 }}
    syncOptions:
      - Replace=true
