name: Deploy and Test

on:
  pull_request:
    paths:
      - '**'
  workflow_dispatch:

jobs:
  kubeval:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Run kubeval
        env:
          KUBERNETES_VERSION: 1.18.1
        run: .github/kubeval.sh
  deploy:
    runs-on: ubuntu-latest
    needs:
      - kubeval
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Create kind cluster
        uses: engineerd/setup-kind@v0.5.0
      - name: Testing Cluster
        run: |
          kubectl cluster-info
          kubectl get pods -n kube-system
          echo "current-context:" $(kubectl config current-context)
          echo "environment-kubeconfig:" ${KUBECONFIG}
#      - name: init
#        run: .github/init.sh
