name: Deploy and Test

on:
  pull_request:
    paths:
      - '**'
  workflow_dispatch:

jobs:
  kubeval:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Run kubeval
        env:
          KUBERNETES_VERSION: 1.18.1
        run: .github/kubeval.sh
